### ISSUE TITLE
feature request : Add biometric identification

### ISSUE THREAD

**Issue by grrosminet** [nextcloud/passman-android#171]
Hi,

You should add biometric identification to make the app more comfortable to use.
It's possible to store the vault password (!!!!) but it's a big security failure !

Thanks

**Comment by binsky08** [comment]
Hmm, what exactly would you like to protect by biometric identification?
You can already enable the android authentification ( which can be biometric - fingerprint or pin on my device) as app access restriction.

Since you can choose whether to store the vault password or not (disabled by default), it's not such a big security failure.
The feature is also described in the faq here: https://github.com/nextcloud/passman-android/blob/master/FAQ.md#how-far-can-i-trust-the-local-storage-encryption-is-it-save-to-store-my-vault-password-on-the-device

**Comment by grrosminet** [comment]
Without biometric identification, you have the choice between :
- refusing to share your device because you have stored the password (so you cannot left your device in other hands than yours when it's unlocked) + a malicious process has more chances to get access to your master password than with biometics
- typing your long master password each time you need a password


With biometric identification , you don't have to worry about that

3 juil. 2024 12:45:30 Timo Triebensky ***@***.***>:
